# Generated by Django 5.2.6 on 2025-09-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParsedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("source", models.CharField(max_length=100)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["name"], name="price_parse_name_d8324c_idx")],
            },
        ),
        migrations.CreateModel(
            name="ParsedProductArchive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("source", models.CharField(max_length=100)),
                ("fetched_at", models.DateTimeField()),
            ],
            options={
                "indexes": [models.Index(fields=["name"], name="price_parse_name_f554c0_idx")],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("leroy_merlen", "Leroy Merlen")], default="leroy_merlen", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("parsed", models.BooleanField(default=False)),
                ("is_main", models.BooleanField(default=False)),
                (
                    "avg_price_lemanapro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Средняя цена Lemanapro (за единицу)",
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("pack_size", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("popularity", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="price_parser.category"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["name"], name="price_parse_name_3fa97a_idx")],
            },
        ),
    ]
