# Generated by Django 5.2.6 on 2025-09-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParsedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("source", models.CharField(default="lemanapro", max_length=100)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParsedProductArchive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("source", models.CharField(default="lemanapro", max_length=50)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParserSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[("Lemana Pro", "Lemana Pro"), ("Ozon", "Ozon"), ("Yandex", "Yandex")],
                        default="Lemana Pro",
                        max_length=255,
                        verbose_name="Площадка",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название парсера")),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("manual", models.BooleanField(default=False)),
                ("interval", models.CharField(default="6h", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "source",
                    models.CharField(choices=[("lemanapro", "LemanaPro")], default="leroy_merlen", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("parsed", models.BooleanField(default=False)),
                ("is_main", models.BooleanField(default=False)),
                (
                    "avg_price_lemanapro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Средняя цена Lemanapro (за единицу)",
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("pack_size", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("popularity", models.IntegerField(default=0)),
            ],
        ),
    ]
