# Generated by Django 5.2.6 on 2025-09-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParserSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название парсера")),
                ("platform", models.CharField(default="Lemana Pro", max_length=255, verbose_name="Площадка")),
                ("schedule", models.CharField(max_length=255, verbose_name="Расписание (cron)")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
