# Generated by Django 5.2.6 on 2025-09-23 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("price_parser", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parserschedule",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="price_parser.category"
            ),
        ),
        migrations.AddField(
            model_name="parserschedule",
            name="products",
            field=models.ManyToManyField(blank=True, related_name="parsers", to="price_parser.product"),
        ),
        migrations.AddField(
            model_name="parsedproductarchive",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parsed_products_archive",
                to="price_parser.product",
            ),
        ),
        migrations.AddField(
            model_name="parsedproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parsed_products",
                to="price_parser.product",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="price_parse_name_3fa97a_idx"),
        ),
        migrations.AddIndex(
            model_name="parsedproductarchive",
            index=models.Index(fields=["name"], name="price_parse_name_f554c0_idx"),
        ),
        migrations.AddIndex(
            model_name="parsedproduct",
            index=models.Index(fields=["name"], name="price_parse_name_d8324c_idx"),
        ),
    ]
