# Generated by Django 5.2.6 on 2025-09-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parser",
            name="platform",
            field=models.CharField(default="Lemana Pro", max_length=255, verbose_name="Площадка"),
        ),
    ]
