# Generated by Django 5.2.6 on 2025-09-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedproduct",
            name="pack_size",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="parsedproductarchive",
            name="pack_size",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
