# Generated by Django 5.2.6 on 2025-09-22 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0002_parser_platform"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parserschedule",
            name="manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parserschedule",
            name="products",
            field=models.ManyToManyField(blank=True, related_name="parsers", to="price_parser.product"),
        ),
        migrations.AddField(
            model_name="parserschedule",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Parser",
        ),
    ]
