# Generated by Django 5.2.6 on 2025-09-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0002_parserschedule"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parserschedule",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RemoveField(
            model_name="parserschedule",
            name="schedule",
        ),
        migrations.AddField(
            model_name="parserschedule",
            name="interval",
            field=models.CharField(default="6h", max_length=50),
        ),
        migrations.AddField(
            model_name="parserschedule",
            name="last_run",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
