# Generated by Django 5.2.6 on 2025-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="parsing_done",
            field=models.BooleanField(default=False),
        ),
    ]
