# Generated by Django 5.2.6 on 2025-09-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0004_alter_parserschedule_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parserschedule",
            name="platform",
            field=models.CharField(
                choices=[("Lemana Pro", "Lemana Pro"), ("Ozon", "Ozon"), ("Yandex", "Yandex")],
                default="Lemana Pro",
                max_length=255,
                verbose_name="Площадка",
            ),
        ),
    ]
