# Generated by Django 5.2.6 on 2025-09-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0004_rename_user_parserschedule_owner_parsedproduct_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="source",
            field=models.CharField(choices=[("lemanapro", "LemanaPro")], default="lemanapro", max_length=50),
        ),
    ]
