# Generated by Django 5.2.6 on 2025-09-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0005_alter_product_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedproduct",
            name="parser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parsed_products",
                to="price_parser.parserschedule",
            ),
        ),
    ]
