# Generated by Django 5.2.6 on 2025-09-27 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0007_productpricehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsedproductarchive",
            name="fetched_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
