# Generated by Django 5.2.6 on 2025-09-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0008_alter_parsedproductarchive_fetched_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("inn", models.CharField(max_length=20, verbose_name="ИНН")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контактные данные",
            },
        ),
    ]
