# Generated by Django 5.2.6 on 2025-09-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0009_contact"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Contacts",
        ),
    ]
