# Generated by Django 5.2.6 on 2025-09-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Страна"),
        ),
    ]
